gin: &login
  adapter: mysql2
  encoding: utf8
  username: root
  password: noWires
  <% unless %x{ruby --version}=~/.*\[.*-(cygwin|mswin32)\].*/ %>
  socket: <%= %x{mysql_config --socket}.chop %> #/var/lib/mysql/mysql.sock
  <% end %>

development: &development
  <<: *login
  host: localhost
  database: pos_development