development:
  domain_name: lvh.me
  domain_port: 3000
  use_s3: true
  s3_public_bucket_name: cluey_development
  s3_user_uploads_bucket_name: cluey_development_user_uploads
  s3_user_uploads_asset_host: http://cluey_development_user_uploads.s3.amazonaws.com
  s3_access_key_id: AKIAICNSMYJPXRM2ENDQ
  s3_secret_access_key: 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
  recaptcha_public_key: 6LfpZ9USAAAAAGtq7QkhGraD3_6Spb6tSnAIL4rI
  recaptcha_private_key: 6LfpZ9USAAAAAHh-le2xNBAVeX-P-MWWAVLeCrQK
  google_translate_api_key: AIzaSyBTUOHzAlYtVL8xP9NHh9WsQmMijzws2x4
  in_kiosk_mode: false

test:
  domain_name: lvh.me
  domain_port: 3000
  use_s3: false
  s3_public_bucket_name: cluey_test
  s3_user_uploads_asset_host: http://
  s3_user_uploads_bucket_name: cluey_test_user_uploads
  s3_access_key_id: AKIAIY5ORKJHOQ7C5ZHA
  s3_secret_access_key: 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
  recaptcha_public_key: 6LfpZ9USAAAAAGtq7QkhGraD3_6Spb6tSnAIL4rI
  recaptcha_private_key: 6LfpZ9USAAAAAHh-le2xNBAVeX-P-MWWAVLeCrQK
  google_translate_api_key: AIzaSyBTUOHzAlYtVL8xP9NHh9WsQmMijzws2x4
  in_kiosk_mode: false

production:
  domain_name: lvh.me
  domain_port: 3000
  use_s3: false
  s3_bucket_name: clueypos_production
  s3_user_uploads_asset_host: http://
  s3_access_key_id: AKIAIY5ORKJHOQ7C5ZHA
  s3_secret_access_key: 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
  recaptcha_public_key: 6LfpZ9USAAAAAGtq7QkhGraD3_6Spb6tSnAIL4rI
  recaptcha_private_key: 6LfpZ9USAAAAAHh-le2xNBAVeX-P-MWWAVLeCrQK
  google_translate_api_key: AIzaSyBTUOHzAlYtVL8xP9NHh9WsQmMijzws2x4
  in_kiosk_mode: true
  
heroku_staging:
  domain_name: clueypos-staging.com
  domain_port: 
  use_s3: true
  s3_public_bucket_name: cluey_staging
  s3_user_uploads_bucket_name: cluey_staging_user_uploads
  s3_user_uploads_asset_host: http://cluey_staging_user_uploads.s3.amazonaws.com
  s3_access_key_id: AKIAICNSMYJPXRM2ENDQ
  s3_secret_access_key: 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
  recaptcha_public_key: 6LfpZ9USAAAAAGtq7QkhGraD3_6Spb6tSnAIL4rI
  recaptcha_private_key: 6LfpZ9USAAAAAHh-le2xNBAVeX-P-MWWAVLeCrQK
  google_translate_api_key: AIzaSyBTUOHzAlYtVL8xP9NHh9WsQmMijzws2x4
  in_kiosk_mode: true
  
heroku_production:
  domain_name: cluey.com
  domain_port: 
  use_s3: true
  s3_public_bucket_name: cluey
  s3_user_uploads_bucket_name: cluey_user_uploads
  s3_user_uploads_asset_host: http://cluey_user_uploads.s3.amazonaws.com
  s3_access_key_id: AKIAICNSMYJPXRM2ENDQ
  s3_secret_access_key: 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
  recaptcha_public_key: 6LfqZ9USAAAAALbZX6WnfPDXWt-cF6Rq7Jw08w6r
  recaptcha_private_key: 6LfqZ9USAAAAADhQS_TYLldT-Ohnglt8-N5DaoCW
  google_translate_api_key: AIzaSyBTUOHzAlYtVL8xP9NHh9WsQmMijzws2x4
  in_kiosk_mode: true